// Code generated by entc, DO NOT EDIT.

package emitent

const (
	// Label holds the string label denoting the emitent type in the database.
	Label = "emitent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescr holds the string denoting the descr field in the database.
	FieldDescr = "descr"
	// Table holds the table name of the emitent in the database.
	Table = "emitents"
)

// Columns holds all SQL columns for emitent fields.
var Columns = []string{
	FieldID,
	FieldDescr,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescrValidator is a validator for the "Descr" field. It is called by the builders before save.
	DescrValidator func(string) error
)
