// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/softilium/mb4/ent/divpayout"
	"github.com/softilium/mb4/ent/predicate"
)

// DivPayoutDelete is the builder for deleting a DivPayout entity.
type DivPayoutDelete struct {
	config
	hooks    []Hook
	mutation *DivPayoutMutation
}

// Where appends a list predicates to the DivPayoutDelete builder.
func (dpd *DivPayoutDelete) Where(ps ...predicate.DivPayout) *DivPayoutDelete {
	dpd.mutation.Where(ps...)
	return dpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dpd *DivPayoutDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dpd.hooks) == 0 {
		affected, err = dpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DivPayoutMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dpd.mutation = mutation
			affected, err = dpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dpd.hooks) - 1; i >= 0; i-- {
			if dpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dpd *DivPayoutDelete) ExecX(ctx context.Context) int {
	n, err := dpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dpd *DivPayoutDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: divpayout.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: divpayout.FieldID,
			},
		},
	}
	if ps := dpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dpd.driver, _spec)
}

// DivPayoutDeleteOne is the builder for deleting a single DivPayout entity.
type DivPayoutDeleteOne struct {
	dpd *DivPayoutDelete
}

// Exec executes the deletion query.
func (dpdo *DivPayoutDeleteOne) Exec(ctx context.Context) error {
	n, err := dpdo.dpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{divpayout.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dpdo *DivPayoutDeleteOne) ExecX(ctx context.Context) {
	dpdo.dpd.ExecX(ctx)
}
