// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/softilium/mb4/ent/emitent"
	"github.com/softilium/mb4/ent/industry"
)

// Emitent is the model entity for the Emitent schema.
type Emitent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Descr holds the value of the "Descr" field.
	Descr string `json:"Descr,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmitentQuery when eager-loading is set.
	Edges             EmitentEdges `json:"edges"`
	industry_emitents *string
}

// EmitentEdges holds the relations/edges for other nodes in the graph.
type EmitentEdges struct {
	// Industry holds the value of the Industry edge.
	Industry *Industry `json:"Industry,omitempty"`
	// Tickers holds the value of the Tickers edge.
	Tickers []*Ticker `json:"Tickers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// IndustryOrErr returns the Industry value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmitentEdges) IndustryOrErr() (*Industry, error) {
	if e.loadedTypes[0] {
		if e.Industry == nil {
			// The edge Industry was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: industry.Label}
		}
		return e.Industry, nil
	}
	return nil, &NotLoadedError{edge: "Industry"}
}

// TickersOrErr returns the Tickers value or an error if the edge
// was not loaded in eager-loading.
func (e EmitentEdges) TickersOrErr() ([]*Ticker, error) {
	if e.loadedTypes[1] {
		return e.Tickers, nil
	}
	return nil, &NotLoadedError{edge: "Tickers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Emitent) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case emitent.FieldID:
			values[i] = new(sql.NullInt64)
		case emitent.FieldDescr:
			values[i] = new(sql.NullString)
		case emitent.ForeignKeys[0]: // industry_emitents
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Emitent", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Emitent fields.
func (e *Emitent) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emitent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = int(value.Int64)
		case emitent.FieldDescr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Descr", values[i])
			} else if value.Valid {
				e.Descr = value.String
			}
		case emitent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field industry_emitents", values[i])
			} else if value.Valid {
				e.industry_emitents = new(string)
				*e.industry_emitents = value.String
			}
		}
	}
	return nil
}

// QueryIndustry queries the "Industry" edge of the Emitent entity.
func (e *Emitent) QueryIndustry() *IndustryQuery {
	return (&EmitentClient{config: e.config}).QueryIndustry(e)
}

// QueryTickers queries the "Tickers" edge of the Emitent entity.
func (e *Emitent) QueryTickers() *TickerQuery {
	return (&EmitentClient{config: e.config}).QueryTickers(e)
}

// Update returns a builder for updating this Emitent.
// Note that you need to call Emitent.Unwrap() before calling this method if this Emitent
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Emitent) Update() *EmitentUpdateOne {
	return (&EmitentClient{config: e.config}).UpdateOne(e)
}

// Unwrap unwraps the Emitent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Emitent) Unwrap() *Emitent {
	tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Emitent is not a transactional entity")
	}
	e.config.driver = tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Emitent) String() string {
	var builder strings.Builder
	builder.WriteString("Emitent(")
	builder.WriteString(fmt.Sprintf("id=%v", e.ID))
	builder.WriteString(", Descr=")
	builder.WriteString(e.Descr)
	builder.WriteByte(')')
	return builder.String()
}

// Emitents is a parsable slice of Emitent.
type Emitents []*Emitent

func (e Emitents) config(cfg config) {
	for _i := range e {
		e[_i].config = cfg
	}
}
