// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rs/xid"
	"github.com/softilium/mb4/ent/emitent"
	"github.com/softilium/mb4/ent/industry"
)

// IndustryCreate is the builder for creating a Industry entity.
type IndustryCreate struct {
	config
	mutation *IndustryMutation
	hooks    []Hook
}

// SetDescr sets the "Descr" field.
func (ic *IndustryCreate) SetDescr(s string) *IndustryCreate {
	ic.mutation.SetDescr(s)
	return ic
}

// SetID sets the "id" field.
func (ic *IndustryCreate) SetID(s string) *IndustryCreate {
	ic.mutation.SetID(s)
	return ic
}

// AddEmitentIDs adds the "Emitents" edge to the Emitent entity by IDs.
func (ic *IndustryCreate) AddEmitentIDs(ids ...xid.ID) *IndustryCreate {
	ic.mutation.AddEmitentIDs(ids...)
	return ic
}

// AddEmitents adds the "Emitents" edges to the Emitent entity.
func (ic *IndustryCreate) AddEmitents(e ...*Emitent) *IndustryCreate {
	ids := make([]xid.ID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return ic.AddEmitentIDs(ids...)
}

// Mutation returns the IndustryMutation object of the builder.
func (ic *IndustryCreate) Mutation() *IndustryMutation {
	return ic.mutation
}

// Save creates the Industry in the database.
func (ic *IndustryCreate) Save(ctx context.Context) (*Industry, error) {
	var (
		err  error
		node *Industry
	)
	if len(ic.hooks) == 0 {
		if err = ic.check(); err != nil {
			return nil, err
		}
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IndustryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ic.check(); err != nil {
				return nil, err
			}
			ic.mutation = mutation
			if node, err = ic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			if ic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IndustryCreate) SaveX(ctx context.Context) *Industry {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IndustryCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IndustryCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IndustryCreate) check() error {
	if _, ok := ic.mutation.Descr(); !ok {
		return &ValidationError{Name: "Descr", err: errors.New(`ent: missing required field "Industry.Descr"`)}
	}
	if v, ok := ic.mutation.Descr(); ok {
		if err := industry.DescrValidator(v); err != nil {
			return &ValidationError{Name: "Descr", err: fmt.Errorf(`ent: validator failed for field "Industry.Descr": %w`, err)}
		}
	}
	if v, ok := ic.mutation.ID(); ok {
		if err := industry.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Industry.id": %w`, err)}
		}
	}
	return nil
}

func (ic *IndustryCreate) sqlSave(ctx context.Context) (*Industry, error) {
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Industry.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (ic *IndustryCreate) createSpec() (*Industry, *sqlgraph.CreateSpec) {
	var (
		_node = &Industry{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: industry.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: industry.FieldID,
			},
		}
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.Descr(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: industry.FieldDescr,
		})
		_node.Descr = value
	}
	if nodes := ic.mutation.EmitentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   industry.EmitentsTable,
			Columns: []string{industry.EmitentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: emitent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IndustryCreateBulk is the builder for creating many Industry entities in bulk.
type IndustryCreateBulk struct {
	config
	builders []*IndustryCreate
}

// Save creates the Industry entities in the database.
func (icb *IndustryCreateBulk) Save(ctx context.Context) ([]*Industry, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Industry, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IndustryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IndustryCreateBulk) SaveX(ctx context.Context) []*Industry {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IndustryCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IndustryCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
