// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/softilium/mb4/ent/investaccountcashflow"
	"github.com/softilium/mb4/ent/predicate"
)

// InvestAccountCashflowDelete is the builder for deleting a InvestAccountCashflow entity.
type InvestAccountCashflowDelete struct {
	config
	hooks    []Hook
	mutation *InvestAccountCashflowMutation
}

// Where appends a list predicates to the InvestAccountCashflowDelete builder.
func (iacd *InvestAccountCashflowDelete) Where(ps ...predicate.InvestAccountCashflow) *InvestAccountCashflowDelete {
	iacd.mutation.Where(ps...)
	return iacd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iacd *InvestAccountCashflowDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iacd.hooks) == 0 {
		affected, err = iacd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvestAccountCashflowMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iacd.mutation = mutation
			affected, err = iacd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iacd.hooks) - 1; i >= 0; i-- {
			if iacd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iacd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iacd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (iacd *InvestAccountCashflowDelete) ExecX(ctx context.Context) int {
	n, err := iacd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iacd *InvestAccountCashflowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: investaccountcashflow.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: investaccountcashflow.FieldID,
			},
		},
	}
	if ps := iacd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, iacd.driver, _spec)
}

// InvestAccountCashflowDeleteOne is the builder for deleting a single InvestAccountCashflow entity.
type InvestAccountCashflowDeleteOne struct {
	iacd *InvestAccountCashflowDelete
}

// Exec executes the deletion query.
func (iacdo *InvestAccountCashflowDeleteOne) Exec(ctx context.Context) error {
	n, err := iacdo.iacd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{investaccountcashflow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iacdo *InvestAccountCashflowDeleteOne) ExecX(ctx context.Context) {
	iacdo.iacd.ExecX(ctx)
}
