// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/softilium/mb4/ent/predicate"
	"github.com/softilium/mb4/ent/strategyfilter"
)

// StrategyFilterDelete is the builder for deleting a StrategyFilter entity.
type StrategyFilterDelete struct {
	config
	hooks    []Hook
	mutation *StrategyFilterMutation
}

// Where appends a list predicates to the StrategyFilterDelete builder.
func (sfd *StrategyFilterDelete) Where(ps ...predicate.StrategyFilter) *StrategyFilterDelete {
	sfd.mutation.Where(ps...)
	return sfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sfd *StrategyFilterDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sfd.hooks) == 0 {
		affected, err = sfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StrategyFilterMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sfd.mutation = mutation
			affected, err = sfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sfd.hooks) - 1; i >= 0; i-- {
			if sfd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfd *StrategyFilterDelete) ExecX(ctx context.Context) int {
	n, err := sfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sfd *StrategyFilterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: strategyfilter.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: strategyfilter.FieldID,
			},
		},
	}
	if ps := sfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sfd.driver, _spec)
}

// StrategyFilterDeleteOne is the builder for deleting a single StrategyFilter entity.
type StrategyFilterDeleteOne struct {
	sfd *StrategyFilterDelete
}

// Exec executes the deletion query.
func (sfdo *StrategyFilterDeleteOne) Exec(ctx context.Context) error {
	n, err := sfdo.sfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{strategyfilter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sfdo *StrategyFilterDeleteOne) ExecX(ctx context.Context) {
	sfdo.sfd.ExecX(ctx)
}
