// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rs/xid"
	"github.com/softilium/mb4/domains"
	"github.com/softilium/mb4/ent/predicate"
	"github.com/softilium/mb4/ent/strategy"
	"github.com/softilium/mb4/ent/strategyfactor"
)

// StrategyFactorUpdate is the builder for updating StrategyFactor entities.
type StrategyFactorUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyFactorMutation
}

// Where appends a list predicates to the StrategyFactorUpdate builder.
func (sfu *StrategyFactorUpdate) Where(ps ...predicate.StrategyFactor) *StrategyFactorUpdate {
	sfu.mutation.Where(ps...)
	return sfu
}

// SetLineNum sets the "LineNum" field.
func (sfu *StrategyFactorUpdate) SetLineNum(i int) *StrategyFactorUpdate {
	sfu.mutation.ResetLineNum()
	sfu.mutation.SetLineNum(i)
	return sfu
}

// SetNillableLineNum sets the "LineNum" field if the given value is not nil.
func (sfu *StrategyFactorUpdate) SetNillableLineNum(i *int) *StrategyFactorUpdate {
	if i != nil {
		sfu.SetLineNum(*i)
	}
	return sfu
}

// AddLineNum adds i to the "LineNum" field.
func (sfu *StrategyFactorUpdate) AddLineNum(i int) *StrategyFactorUpdate {
	sfu.mutation.AddLineNum(i)
	return sfu
}

// SetIsUsed sets the "IsUsed" field.
func (sfu *StrategyFactorUpdate) SetIsUsed(b bool) *StrategyFactorUpdate {
	sfu.mutation.SetIsUsed(b)
	return sfu
}

// SetNillableIsUsed sets the "IsUsed" field if the given value is not nil.
func (sfu *StrategyFactorUpdate) SetNillableIsUsed(b *bool) *StrategyFactorUpdate {
	if b != nil {
		sfu.SetIsUsed(*b)
	}
	return sfu
}

// SetRK sets the "RK" field.
func (sfu *StrategyFactorUpdate) SetRK(dv domains.ReportValue) *StrategyFactorUpdate {
	sfu.mutation.ResetRK()
	sfu.mutation.SetRK(dv)
	return sfu
}

// AddRK adds dv to the "RK" field.
func (sfu *StrategyFactorUpdate) AddRK(dv domains.ReportValue) *StrategyFactorUpdate {
	sfu.mutation.AddRK(dv)
	return sfu
}

// SetRVT sets the "RVT" field.
func (sfu *StrategyFactorUpdate) SetRVT(dvt domains.ReportValueType) *StrategyFactorUpdate {
	sfu.mutation.ResetRVT()
	sfu.mutation.SetRVT(dvt)
	return sfu
}

// AddRVT adds dvt to the "RVT" field.
func (sfu *StrategyFactorUpdate) AddRVT(dvt domains.ReportValueType) *StrategyFactorUpdate {
	sfu.mutation.AddRVT(dvt)
	return sfu
}

// SetMinAcceptable sets the "MinAcceptable" field.
func (sfu *StrategyFactorUpdate) SetMinAcceptable(f float64) *StrategyFactorUpdate {
	sfu.mutation.ResetMinAcceptable()
	sfu.mutation.SetMinAcceptable(f)
	return sfu
}

// AddMinAcceptable adds f to the "MinAcceptable" field.
func (sfu *StrategyFactorUpdate) AddMinAcceptable(f float64) *StrategyFactorUpdate {
	sfu.mutation.AddMinAcceptable(f)
	return sfu
}

// SetMaxAcceptable sets the "MaxAcceptable" field.
func (sfu *StrategyFactorUpdate) SetMaxAcceptable(f float64) *StrategyFactorUpdate {
	sfu.mutation.ResetMaxAcceptable()
	sfu.mutation.SetMaxAcceptable(f)
	return sfu
}

// AddMaxAcceptable adds f to the "MaxAcceptable" field.
func (sfu *StrategyFactorUpdate) AddMaxAcceptable(f float64) *StrategyFactorUpdate {
	sfu.mutation.AddMaxAcceptable(f)
	return sfu
}

// SetInverse sets the "Inverse" field.
func (sfu *StrategyFactorUpdate) SetInverse(b bool) *StrategyFactorUpdate {
	sfu.mutation.SetInverse(b)
	return sfu
}

// SetNillableInverse sets the "Inverse" field if the given value is not nil.
func (sfu *StrategyFactorUpdate) SetNillableInverse(b *bool) *StrategyFactorUpdate {
	if b != nil {
		sfu.SetInverse(*b)
	}
	return sfu
}

// SetK sets the "K" field.
func (sfu *StrategyFactorUpdate) SetK(f float64) *StrategyFactorUpdate {
	sfu.mutation.ResetK()
	sfu.mutation.SetK(f)
	return sfu
}

// SetNillableK sets the "K" field if the given value is not nil.
func (sfu *StrategyFactorUpdate) SetNillableK(f *float64) *StrategyFactorUpdate {
	if f != nil {
		sfu.SetK(*f)
	}
	return sfu
}

// AddK adds f to the "K" field.
func (sfu *StrategyFactorUpdate) AddK(f float64) *StrategyFactorUpdate {
	sfu.mutation.AddK(f)
	return sfu
}

// SetGist sets the "Gist" field.
func (sfu *StrategyFactorUpdate) SetGist(f float64) *StrategyFactorUpdate {
	sfu.mutation.ResetGist()
	sfu.mutation.SetGist(f)
	return sfu
}

// SetNillableGist sets the "Gist" field if the given value is not nil.
func (sfu *StrategyFactorUpdate) SetNillableGist(f *float64) *StrategyFactorUpdate {
	if f != nil {
		sfu.SetGist(*f)
	}
	return sfu
}

// AddGist adds f to the "Gist" field.
func (sfu *StrategyFactorUpdate) AddGist(f float64) *StrategyFactorUpdate {
	sfu.mutation.AddGist(f)
	return sfu
}

// SetStrategyID sets the "Strategy" edge to the Strategy entity by ID.
func (sfu *StrategyFactorUpdate) SetStrategyID(id xid.ID) *StrategyFactorUpdate {
	sfu.mutation.SetStrategyID(id)
	return sfu
}

// SetStrategy sets the "Strategy" edge to the Strategy entity.
func (sfu *StrategyFactorUpdate) SetStrategy(s *Strategy) *StrategyFactorUpdate {
	return sfu.SetStrategyID(s.ID)
}

// Mutation returns the StrategyFactorMutation object of the builder.
func (sfu *StrategyFactorUpdate) Mutation() *StrategyFactorMutation {
	return sfu.mutation
}

// ClearStrategy clears the "Strategy" edge to the Strategy entity.
func (sfu *StrategyFactorUpdate) ClearStrategy() *StrategyFactorUpdate {
	sfu.mutation.ClearStrategy()
	return sfu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sfu *StrategyFactorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sfu.hooks) == 0 {
		if err = sfu.check(); err != nil {
			return 0, err
		}
		affected, err = sfu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StrategyFactorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sfu.check(); err != nil {
				return 0, err
			}
			sfu.mutation = mutation
			affected, err = sfu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sfu.hooks) - 1; i >= 0; i-- {
			if sfu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sfu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sfu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sfu *StrategyFactorUpdate) SaveX(ctx context.Context) int {
	affected, err := sfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sfu *StrategyFactorUpdate) Exec(ctx context.Context) error {
	_, err := sfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfu *StrategyFactorUpdate) ExecX(ctx context.Context) {
	if err := sfu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfu *StrategyFactorUpdate) check() error {
	if v, ok := sfu.mutation.LineNum(); ok {
		if err := strategyfactor.LineNumValidator(v); err != nil {
			return &ValidationError{Name: "LineNum", err: fmt.Errorf(`ent: validator failed for field "StrategyFactor.LineNum": %w`, err)}
		}
	}
	if _, ok := sfu.mutation.StrategyID(); sfu.mutation.StrategyCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "StrategyFactor.Strategy"`)
	}
	return nil
}

func (sfu *StrategyFactorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   strategyfactor.Table,
			Columns: strategyfactor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: strategyfactor.FieldID,
			},
		},
	}
	if ps := sfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfu.mutation.LineNum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldLineNum,
		})
	}
	if value, ok := sfu.mutation.AddedLineNum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldLineNum,
		})
	}
	if value, ok := sfu.mutation.IsUsed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: strategyfactor.FieldIsUsed,
		})
	}
	if value, ok := sfu.mutation.RK(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRK,
		})
	}
	if value, ok := sfu.mutation.AddedRK(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRK,
		})
	}
	if value, ok := sfu.mutation.RVT(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRVT,
		})
	}
	if value, ok := sfu.mutation.AddedRVT(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRVT,
		})
	}
	if value, ok := sfu.mutation.MinAcceptable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMinAcceptable,
		})
	}
	if value, ok := sfu.mutation.AddedMinAcceptable(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMinAcceptable,
		})
	}
	if value, ok := sfu.mutation.MaxAcceptable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMaxAcceptable,
		})
	}
	if value, ok := sfu.mutation.AddedMaxAcceptable(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMaxAcceptable,
		})
	}
	if value, ok := sfu.mutation.Inverse(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: strategyfactor.FieldInverse,
		})
	}
	if value, ok := sfu.mutation.K(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldK,
		})
	}
	if value, ok := sfu.mutation.AddedK(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldK,
		})
	}
	if value, ok := sfu.mutation.Gist(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldGist,
		})
	}
	if value, ok := sfu.mutation.AddedGist(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldGist,
		})
	}
	if sfu.mutation.StrategyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategyfactor.StrategyTable,
			Columns: []string{strategyfactor.StrategyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: strategy.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfu.mutation.StrategyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategyfactor.StrategyTable,
			Columns: []string{strategyfactor.StrategyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: strategy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategyfactor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// StrategyFactorUpdateOne is the builder for updating a single StrategyFactor entity.
type StrategyFactorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyFactorMutation
}

// SetLineNum sets the "LineNum" field.
func (sfuo *StrategyFactorUpdateOne) SetLineNum(i int) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetLineNum()
	sfuo.mutation.SetLineNum(i)
	return sfuo
}

// SetNillableLineNum sets the "LineNum" field if the given value is not nil.
func (sfuo *StrategyFactorUpdateOne) SetNillableLineNum(i *int) *StrategyFactorUpdateOne {
	if i != nil {
		sfuo.SetLineNum(*i)
	}
	return sfuo
}

// AddLineNum adds i to the "LineNum" field.
func (sfuo *StrategyFactorUpdateOne) AddLineNum(i int) *StrategyFactorUpdateOne {
	sfuo.mutation.AddLineNum(i)
	return sfuo
}

// SetIsUsed sets the "IsUsed" field.
func (sfuo *StrategyFactorUpdateOne) SetIsUsed(b bool) *StrategyFactorUpdateOne {
	sfuo.mutation.SetIsUsed(b)
	return sfuo
}

// SetNillableIsUsed sets the "IsUsed" field if the given value is not nil.
func (sfuo *StrategyFactorUpdateOne) SetNillableIsUsed(b *bool) *StrategyFactorUpdateOne {
	if b != nil {
		sfuo.SetIsUsed(*b)
	}
	return sfuo
}

// SetRK sets the "RK" field.
func (sfuo *StrategyFactorUpdateOne) SetRK(dv domains.ReportValue) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetRK()
	sfuo.mutation.SetRK(dv)
	return sfuo
}

// AddRK adds dv to the "RK" field.
func (sfuo *StrategyFactorUpdateOne) AddRK(dv domains.ReportValue) *StrategyFactorUpdateOne {
	sfuo.mutation.AddRK(dv)
	return sfuo
}

// SetRVT sets the "RVT" field.
func (sfuo *StrategyFactorUpdateOne) SetRVT(dvt domains.ReportValueType) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetRVT()
	sfuo.mutation.SetRVT(dvt)
	return sfuo
}

// AddRVT adds dvt to the "RVT" field.
func (sfuo *StrategyFactorUpdateOne) AddRVT(dvt domains.ReportValueType) *StrategyFactorUpdateOne {
	sfuo.mutation.AddRVT(dvt)
	return sfuo
}

// SetMinAcceptable sets the "MinAcceptable" field.
func (sfuo *StrategyFactorUpdateOne) SetMinAcceptable(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetMinAcceptable()
	sfuo.mutation.SetMinAcceptable(f)
	return sfuo
}

// AddMinAcceptable adds f to the "MinAcceptable" field.
func (sfuo *StrategyFactorUpdateOne) AddMinAcceptable(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.AddMinAcceptable(f)
	return sfuo
}

// SetMaxAcceptable sets the "MaxAcceptable" field.
func (sfuo *StrategyFactorUpdateOne) SetMaxAcceptable(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetMaxAcceptable()
	sfuo.mutation.SetMaxAcceptable(f)
	return sfuo
}

// AddMaxAcceptable adds f to the "MaxAcceptable" field.
func (sfuo *StrategyFactorUpdateOne) AddMaxAcceptable(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.AddMaxAcceptable(f)
	return sfuo
}

// SetInverse sets the "Inverse" field.
func (sfuo *StrategyFactorUpdateOne) SetInverse(b bool) *StrategyFactorUpdateOne {
	sfuo.mutation.SetInverse(b)
	return sfuo
}

// SetNillableInverse sets the "Inverse" field if the given value is not nil.
func (sfuo *StrategyFactorUpdateOne) SetNillableInverse(b *bool) *StrategyFactorUpdateOne {
	if b != nil {
		sfuo.SetInverse(*b)
	}
	return sfuo
}

// SetK sets the "K" field.
func (sfuo *StrategyFactorUpdateOne) SetK(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetK()
	sfuo.mutation.SetK(f)
	return sfuo
}

// SetNillableK sets the "K" field if the given value is not nil.
func (sfuo *StrategyFactorUpdateOne) SetNillableK(f *float64) *StrategyFactorUpdateOne {
	if f != nil {
		sfuo.SetK(*f)
	}
	return sfuo
}

// AddK adds f to the "K" field.
func (sfuo *StrategyFactorUpdateOne) AddK(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.AddK(f)
	return sfuo
}

// SetGist sets the "Gist" field.
func (sfuo *StrategyFactorUpdateOne) SetGist(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.ResetGist()
	sfuo.mutation.SetGist(f)
	return sfuo
}

// SetNillableGist sets the "Gist" field if the given value is not nil.
func (sfuo *StrategyFactorUpdateOne) SetNillableGist(f *float64) *StrategyFactorUpdateOne {
	if f != nil {
		sfuo.SetGist(*f)
	}
	return sfuo
}

// AddGist adds f to the "Gist" field.
func (sfuo *StrategyFactorUpdateOne) AddGist(f float64) *StrategyFactorUpdateOne {
	sfuo.mutation.AddGist(f)
	return sfuo
}

// SetStrategyID sets the "Strategy" edge to the Strategy entity by ID.
func (sfuo *StrategyFactorUpdateOne) SetStrategyID(id xid.ID) *StrategyFactorUpdateOne {
	sfuo.mutation.SetStrategyID(id)
	return sfuo
}

// SetStrategy sets the "Strategy" edge to the Strategy entity.
func (sfuo *StrategyFactorUpdateOne) SetStrategy(s *Strategy) *StrategyFactorUpdateOne {
	return sfuo.SetStrategyID(s.ID)
}

// Mutation returns the StrategyFactorMutation object of the builder.
func (sfuo *StrategyFactorUpdateOne) Mutation() *StrategyFactorMutation {
	return sfuo.mutation
}

// ClearStrategy clears the "Strategy" edge to the Strategy entity.
func (sfuo *StrategyFactorUpdateOne) ClearStrategy() *StrategyFactorUpdateOne {
	sfuo.mutation.ClearStrategy()
	return sfuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sfuo *StrategyFactorUpdateOne) Select(field string, fields ...string) *StrategyFactorUpdateOne {
	sfuo.fields = append([]string{field}, fields...)
	return sfuo
}

// Save executes the query and returns the updated StrategyFactor entity.
func (sfuo *StrategyFactorUpdateOne) Save(ctx context.Context) (*StrategyFactor, error) {
	var (
		err  error
		node *StrategyFactor
	)
	if len(sfuo.hooks) == 0 {
		if err = sfuo.check(); err != nil {
			return nil, err
		}
		node, err = sfuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StrategyFactorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sfuo.check(); err != nil {
				return nil, err
			}
			sfuo.mutation = mutation
			node, err = sfuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sfuo.hooks) - 1; i >= 0; i-- {
			if sfuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sfuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sfuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sfuo *StrategyFactorUpdateOne) SaveX(ctx context.Context) *StrategyFactor {
	node, err := sfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sfuo *StrategyFactorUpdateOne) Exec(ctx context.Context) error {
	_, err := sfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfuo *StrategyFactorUpdateOne) ExecX(ctx context.Context) {
	if err := sfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfuo *StrategyFactorUpdateOne) check() error {
	if v, ok := sfuo.mutation.LineNum(); ok {
		if err := strategyfactor.LineNumValidator(v); err != nil {
			return &ValidationError{Name: "LineNum", err: fmt.Errorf(`ent: validator failed for field "StrategyFactor.LineNum": %w`, err)}
		}
	}
	if _, ok := sfuo.mutation.StrategyID(); sfuo.mutation.StrategyCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "StrategyFactor.Strategy"`)
	}
	return nil
}

func (sfuo *StrategyFactorUpdateOne) sqlSave(ctx context.Context) (_node *StrategyFactor, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   strategyfactor.Table,
			Columns: strategyfactor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: strategyfactor.FieldID,
			},
		},
	}
	id, ok := sfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StrategyFactor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategyfactor.FieldID)
		for _, f := range fields {
			if !strategyfactor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategyfactor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfuo.mutation.LineNum(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldLineNum,
		})
	}
	if value, ok := sfuo.mutation.AddedLineNum(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldLineNum,
		})
	}
	if value, ok := sfuo.mutation.IsUsed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: strategyfactor.FieldIsUsed,
		})
	}
	if value, ok := sfuo.mutation.RK(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRK,
		})
	}
	if value, ok := sfuo.mutation.AddedRK(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRK,
		})
	}
	if value, ok := sfuo.mutation.RVT(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRVT,
		})
	}
	if value, ok := sfuo.mutation.AddedRVT(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: strategyfactor.FieldRVT,
		})
	}
	if value, ok := sfuo.mutation.MinAcceptable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMinAcceptable,
		})
	}
	if value, ok := sfuo.mutation.AddedMinAcceptable(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMinAcceptable,
		})
	}
	if value, ok := sfuo.mutation.MaxAcceptable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMaxAcceptable,
		})
	}
	if value, ok := sfuo.mutation.AddedMaxAcceptable(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldMaxAcceptable,
		})
	}
	if value, ok := sfuo.mutation.Inverse(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: strategyfactor.FieldInverse,
		})
	}
	if value, ok := sfuo.mutation.K(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldK,
		})
	}
	if value, ok := sfuo.mutation.AddedK(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldK,
		})
	}
	if value, ok := sfuo.mutation.Gist(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldGist,
		})
	}
	if value, ok := sfuo.mutation.AddedGist(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: strategyfactor.FieldGist,
		})
	}
	if sfuo.mutation.StrategyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategyfactor.StrategyTable,
			Columns: []string{strategyfactor.StrategyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: strategy.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfuo.mutation.StrategyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   strategyfactor.StrategyTable,
			Columns: []string{strategyfactor.StrategyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: strategy.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StrategyFactor{config: sfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategyfactor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
