// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DivPayout is the predicate function for divpayout builders.
type DivPayout func(*sql.Selector)

// Emitent is the predicate function for emitent builders.
type Emitent func(*sql.Selector)

// Industry is the predicate function for industry builders.
type Industry func(*sql.Selector)

// InvestAccount is the predicate function for investaccount builders.
type InvestAccount func(*sql.Selector)

// InvestAccountCashflow is the predicate function for investaccountcashflow builders.
type InvestAccountCashflow func(*sql.Selector)

// InvestAccountValuation is the predicate function for investaccountvaluation builders.
type InvestAccountValuation func(*sql.Selector)

// Quote is the predicate function for quote builders.
type Quote func(*sql.Selector)

// Ticker is the predicate function for ticker builders.
type Ticker func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
